### ISSUE TITLE
Number is too big to encode warning

### ISSUE THREAD

**Issue by DanielChabrowski** [JonathanWilbur/vscode-asn1#2]
Hello,
This extension assumes that INTEGER is saved on 32bit signed integer, however, our use case is that it's both unsigned and 64bit. Some kind of configuration letting user select what kind of type is used for integer could resolve this little issue.

Also, thanks for the extension :)

Edit: Sorry, usage of unsigned or signed should depend on the range, not configuration.

**Comment by JonathanWilbur** [comment]
Hey again, @DanielChabrowski ! Thanks again for your feedback.

I see your point, however, this was a very intentional part of this extension. The reason I used 32-bit signed extremes for the threshold is that a 32-bit machine is still liable to be encountered in the present day, and hence, there may be a case in which an ASN.1 codec may not be able to digest an `INTEGER` larger than the 32-bit signed extrema. Even that notwithstanding, some 64-bit machines may fail to decode `INTEGER`s greater than the signed 32-bit extrema. Even my own ASN.1 TypeScript library does not decode numbers greater than the signed 32-bit extrema as a result of limitations in the language itself. So I think this extension is still well-authored in warning you about that potential issue.

However, I can see your frustration with having a bunch of warnings all over your screen when you _know_ you will not be sending potentially 64-bit integers to an endpoint that cannot handle them, so I added a configuration option `asn1.ignoreIntegerSize` that will allow you to turn this off. You should see this feature included in the newer version, which is soon to be published.
